# /usr/local/lib/Bash-utils/install/.Bash-utils/config/initializer/locale/en.locale
# /usr/local/lib/Bash-utils/lib/functions/main/Args.lib
# /usr/local/lib/Bash-utils/lib/functions/main/BasicMaths.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Case.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Checkings.lib
# /usr/local/lib/Bash-utils/lib/functions/main/CMDS.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Colors.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Decho.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Directories.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Echo.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Errors.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Files.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Filesystem.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Headers.lib
# /usr/local/lib/Bash-utils/lib/functions/main/OS.lib
# /usr/local/lib/Bash-utils/lib/functions/main/PosixTerm.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Status.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Text.lib
# /usr/local/lib/Bash-utils/lib/functions/main/Time.lib
# /home/dimob/.Bash-utils/config/modules/main/Aliases.conf
# /home/dimob/.Bash-utils/config/modules/main/colors.conf
# /home/dimob/.Bash-utils/config/modules/main/debug.conf
# /home/dimob/.Bash-utils/config/modules/main/Exit.conf
# /home/dimob/.Bash-utils/config/modules/main/Filesystem.conf
# /home/dimob/.Bash-utils/config/modules/main/module.conf
# /home/dimob/.Bash-utils/config/modules/main/Project.conf
# /home/dimob/.Bash-utils/config/modules/main/Status.conf
# /home/dimob/.Bash-utils/config/modules/main/text.conf
# /home/dimob/.Bash-utils/config/modules/main/time.conf
# /home/dimob/.Bash-utils/modules/main/Initializer.sh
# /usr/local/lib/Bash-utils/install/.Bash-utils/config/initializer/Status.conf
# /home/dimob/Bash-utils-init.sh
