#!/usr/bin/env bash

## BASH-UTILS PATHS DEFINITIONS

# Bash-Utils root directory path.
BASH_UTILS_ROOT="/usr/local/lib/Bash-utils"

# Bash-Utils sub-folders paths.
BASH_UTILS="$BASH_UTILS_ROOT/lib"
BASH_UTILS_BIN="$BASH_UTILS_ROOT/bin"
BASH_UTILS_CONF="$BASH_UTILS_ROOT/config"
BASH_UTILS_TMP="$BASH_UTILS_ROOT/tmp"

# "config" folder's content.
BASH_UTILS_CONF_PROJECT_STATUS="$BASH_UTILS_CONF/ProjectStatus.conf"

# Bash-utils dev-tools paths.
BASH_UTILS_DEVTOOLS_ROOT="$BASH_UTILS_ROOT/projects/dev-tools"
BASH_UTILS_DEVTOOLS_BIN="$BASH_UTILS_DEVTOOLS_ROOT/dev-bin"
BASH_UTILS_DEVTOOLS_IMG="$BASH_UTILS_DEVTOOLS_ROOT/dev-img"
BASH_UTILS_DEVTOOLS_SRC="$BASH_UTILS_DEVTOOLS_ROOT/dev-src"
BASH_UTILS_DEVTOOLS_TRANSL="$BASH_UTILS_DEVTOOLS_ROOT/dev-translations"

# "lib" folder's content.
BASH_UTILS_FUNCTS="$BASH_UTILS/functions"
BASH_UTILS_FUNCTS_BASIS="$BASH_UTILS_FUNCTS/basis"
BASH_UTILS_LANG="$BASH_UTILS/lang"
BASH_UTILS_VARS="$BASH_UTILS/variables"

# -----------------------------------------------

## ADDING THE ABOVE PATHS IN THE "$PATH" ENVIRONMENT VARIABLE.
function ExportPaths
{
    #***** Parameters *****
    p_path=$1

    #***** Code *****
    export PATH=$PATH:$p_path
}

# ExportPaths "$BASH_UTILS_ROOT"
# ExportPaths "$BASH_UTILS"
# ExportPaths "$BASH_UTILS_BIN"
# ExportPaths "$BASH_UTILS_CONF"
# ExportPaths "$BASH_UTILS_CONF_PROJECT_STATUS"
# ExportPaths "$BASH_UTILS_DEVTOOLS_ROOT"
# ExportPaths "$BASH_UTILS_DEVTOOLS_BIN"
# ExportPaths "$BASH_UTILS_DEVTOOLS_IMG"
# ExportPaths "$BASH_UTILS_DEVTOOLS_SRC"
# ExportPaths "$BASH_UTILS_DEVTOOLS_TRANSL"
# ExportPaths "$BASH_UTILS_FUNCTS"
# ExportPaths "$BASH_UTILS_FUNCTS_BASIS"
# ExportPaths "$BASH_UTILS_LANG"
# ExportPaths "$BASH_UTILS_TMP"
# ExportPaths "$BASH_UTILS_VARS"
