#!/usr/bin/env bash

# ----------------------------------------
# DEV-TOOLS EXECUTABLE FILE INFORMATIONS :

# Name          : latex-clean.sh
# Author(s)     : Dimitri Obeid
# Version       : 1.0

# ------------------
# FILE DESCRIPTION :

# This script remove every files generated by the LaTeX software developments, except the ".tex" (LaTeX source files) and PDF files.

# -----------------------------------------------



# /////////////////////////////////////////////////////////////////////////////////////////////// #

# ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; #

######################################################### CODE ########################################################

find docs/ -name "*.aux" "*.log" "*.out" "*.synctex.gz" "*.toc" -exec rm {} +
